server:
  port: 7002

spring.data.mongodb:
  host: 192.168.1.99
  port: 27017
  database: recommendation-db
  username: root
  password: "@Chudeptrai123"
  authentication-database: admin

logging:
  level:
    root: INFO
    mc.microservices: DEBUG
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb
server:
  port: 8080
