version: '2.1'

services:
  product:
    build: microservices/product-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb

  recommendation:
    build: microservices/recommendation-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb


  review:
    build: microservices/review-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres:
        condition: service_healthy

  product-composite:
    build: microservices/product-composite-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  mongodb:
    image: mongo:6.0.8
    ports:
      - "27017:27017"
    command: mongod
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "@Chudeptrai123"
      MONGO_INITDB_DATABASE: "product-db"

  postgres:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: mc
      POSTGRES_PASSWORD: Chudeptrai123
      POSTGRES_DB: review-db
    ports:
      - 5432:5432
    healthcheck:
      test: "pg_isready -U mc"
      interval: 5s
      timeout: 2s
      retries: 60