server:
  port: 7001

spring.data.mongodb:
  host: 192.168.1.99
  port: 27017
  database: product-db
  username: root
  password: "@Chudeptrai123"
  authentication-database: admin

logging:
  level:
    root: INFO
    mc.microservices: DEBUG
---

spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb
      database: product-db
      username: root
      password: "@Chudeptrai123"
server:
  port: 8080