server:
  port: 7001

spring.data.mongodb:
  host: 192.168.1.99
  port: 27017
  database: product-db
  username: root
  password: "@Chudeptrai123"
  authentication-database: admin

logging:
  level:
    root: INFO
    mc.microservices: DEBUG
spring:
  cloud:
    stream:
      default-binder: rabbit
      bindings:
        messageProcessor-in-0:
          destination: products
      kafka:
        binder:
          brokers: 192.168.1.99:9092
  rabbitmq:
    host: 192.168.1.99
    port: 5672
    username: guest
    password: guest

---

spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb
      database: product-db
      username: root
      password: "@Chudeptrai123"

  cloud:
    stream:
      default-binder: rabbit
      bindings:
        messageProcessor-in-0:
          destination: products
      kafka:
        binder:
          brokers: kafka
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
server:
  port: 8080